title: KSR - KW Sport Racing track days at Grand Bend Motorplex
name: KW Sport Racing
email: kwsportracing@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  KW Sport Racing motorcycle track days in Ontario. KSR runs track days exclusively at Grand Bend Motorplex. See you on the track!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

instagram: https://www.instagram.com/ksrcanada/
facebook: https://www.facebook.com/groups/KWSportRacing/

registration: /dates

# Build settings
theme: minima
plugins:
  - jekyll-feed
